version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
